(()=>{
const $=id=>document.getElementById(id);
const page=$('page-activity');
if(!page)return;
page.className='page px-5 pt-5 pb-8 space-y-5';
page.innerHTML=`<div><div class="section-label">MY ACTIVITY</div><h1 class="text-xl font-black mt-1">あなたの活動記録</h1><p class="text-xs text-slate-400 mt-2">続けてきたことを、少しずつ振り返れます。</p></div>
<div id="activitySummary" class="grid grid-cols-3 gap-2"><div class="card p-3 text-center"><div class="text-xl font-black">—</div><div class="text-[9px] font-bold text-slate-400 mt-1">今月</div></div><div class="card p-3 text-center"><div class="text-xl font-black">—</div><div class="text-[9px] font-bold text-slate-400 mt-1">累計</div></div><div class="card p-3 text-center"><div class="text-xl font-black">—</div><div class="text-[9px] font-bold text-slate-400 mt-1">継続</div></div></div>
<div class="card p-5"><div class="flex items-center justify-between"><button id="calPrev" class="w-9 h-9 rounded-xl bg-slate-100 text-slate-500">‹</button><div id="calTitle" class="font-black text-sm"></div><button id="calNext" class="w-9 h-9 rounded-xl bg-slate-100 text-slate-500">›</button></div><div class="grid grid-cols-7 text-center text-[9px] font-bold text-slate-400 mt-4"><span>月</span><span>火</span><span>水</span><span>木</span><span>金</span><span>土</span><span>日</span></div><div id="activityCalendar" class="grid grid-cols-7 gap-y-2 mt-2"></div><div class="flex items-center gap-2 mt-4 text-[10px] text-slate-400"><span class="w-2.5 h-2.5 rounded-full bg-accent"></span>参加した日</div></div>
<div id="milestoneCard" class="card p-5"></div>
<div class="card p-5"><div class="section-label">RECENT ACTIVITY</div><h2 class="text-base font-black mt-1">最近の活動</h2><div id="recentActivityMember" class="mt-3"></div></div>
<div class="card p-5"><div class="section-label">YOUR JOURNEY</div><h2 class="text-base font-black mt-1">これまでの軌跡</h2><div id="journeyList" class="mt-4"></div></div>`;
let records=[],calDate=new Date();
const ym=r=>r.activity_date.slice(0,7), md=s=>{const d=new Date(s+'T00:00:00');return `${d.getMonth()+1}月${d.getDate()}日`}, dm=(a,b)=>(a.getFullYear()-b.getFullYear())*12+a.getMonth()-b.getMonth();
function streak(){let ms=[...new Set(records.map(ym))].sort();if(!ms.length)return 0;let run=1;for(let i=ms.length-1;i>0;i--){if(dm(new Date(ms[i]+'-01'),new Date(ms[i-1]+'-01'))===1)run++;else break}let latest=new Date(ms.at(-1)+'-01'),now=new Date();return dm(new Date(now.getFullYear(),now.getMonth(),1),latest)<=1?run:0}
function next(n){for(const x of [1,5,10,20,30,50,75,100])if(n<x)return x;return Math.ceil((n+1)/50)*50}
function summary(){let now=new Date(),key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`,m=records.filter(r=>ym(r)===key).length,s=streak();$('activitySummary').innerHTML=`<div class="card p-3 text-center"><div class="text-xl font-black">${m}<span class="text-[10px] ml-1 text-slate-400">回</span></div><div class="text-[9px] font-bold text-slate-400 mt-1">今月</div></div><div class="card p-3 text-center"><div class="text-xl font-black">${records.length}<span class="text-[10px] ml-1 text-slate-400">回</span></div><div class="text-[9px] font-bold text-slate-400 mt-1">累計</div></div><div class="card p-3 text-center"><div class="text-xl font-black">${s?s:'—'}${s?'<span class="text-[10px] ml-1 text-slate-400">か月</span>':''}</div><div class="text-[9px] font-bold text-slate-400 mt-1">${s?'継続中':'またここから'}</div></div>`}
function calendar(){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7,key=`${y}-${String(m+1).padStart(2,'0')}`,active=new Set(records.filter(r=>ym(r)===key).map(r=>+r.activity_date.slice(8,10)));$('calTitle').textContent=`${y}年 ${m+1}月`;let h='<span></span>'.repeat(off);for(let d=1;d<=days;d++)h+=`<div class="h-8 grid place-items-center"><span class="w-7 h-7 rounded-full grid place-items-center text-[11px] font-bold ${active.has(d)?'bg-accent text-white':'text-slate-600'}">${d}</span></div>`;$('activityCalendar').innerHTML=h}
$('calPrev').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);calendar()};$('calNext').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);calendar()};
function milestone(){let n=records.length,nx=next(n),marks=[0,1,5,10,20,30,50,75,100],prev=marks.filter(x=>x<=n).at(-1)||0,p=Math.max(0,Math.min(100,Math.round((n-prev)/(nx-prev)*100)));$('milestoneCard').innerHTML=`<div class="section-label">NEXT MILESTONE</div><div class="flex justify-between items-end mt-1 gap-3"><div><h2 class="text-base font-black">${n?`あと${nx-n}回で${nx}回参加！`:'最初の1回からスタート'}</h2><p class="text-[10px] text-slate-400 mt-1">自分のペースで、少しずつ。</p></div><div class="text-sm font-black accent whitespace-nowrap">${n} / ${nx}</div></div><div class="h-2 rounded-full bg-slate-100 overflow-hidden mt-4"><div class="h-full bg-accent rounded-full" style="width:${p}%"></div></div>`}
function recent(){$('recentActivityMember').innerHTML=records.slice(0,5).map(r=>`<div class="py-3 border-t first:border-t-0 border-slate-100"><div class="text-[10px] font-bold text-slate-400">${md(r.activity_date)}</div><div class="text-sm font-black mt-1">${String(r.title||'BizFit').replace(/[<>&]/g,'')}</div>${r.minutes?`<div class="text-[10px] text-slate-400 mt-1">${r.minutes}分</div>`:''}</div>`).join('')||'<p class="text-xs text-slate-400 py-4">まだ活動記録はありません。最初の参加からここに記録されます。</p>'}
function journey(){if(!records.length){$('journeyList').innerHTML='<p class="text-xs text-slate-400">これからの活動がここに積み重なっていきます。</p>';return}let a=[...records].sort((x,y)=>x.activity_date.localeCompare(y.activity_date)),out=[{date:a[0].activity_date,title:'BizFit START!',body:'はじめてBizFitに参加しました。'}];[5,10,20,30,50,75,100].forEach(n=>{if(a.length>=n)out.push({date:a[n-1].activity_date,title:`${n}回参加`,body:`参加回数が${n}回になりました。`})});let ms=[...new Set(a.map(ym))].sort(),run=0,last=null,done=new Set();for(const k of ms){let d=new Date(k+'-01');run=last&&dm(d,last)===1?run+1:1;last=d;[3,6,12,24,36].forEach(n=>{if(run===n&&!done.has(n)){done.add(n);let r=a.filter(x=>ym(x)===k).at(-1);out.push({date:r.activity_date,title:`${n}か月継続`,body:`${n}か月続けて参加しました。`})}})}out.sort((x,y)=>y.date.localeCompare(x.date));$('journeyList').innerHTML=out.map((x,i)=>`<div class="relative pl-6 pb-5"><span class="absolute left-0 top-1 w-2.5 h-2.5 rounded-full bg-accent"></span>${i<out.length-1?'<span class="absolute left-[4px] top-3 bottom-0 border-l border-orange-200"></span>':''}<div class="text-[9px] font-bold text-slate-400">${x.date.replace(/-/g,'.')}</div><div class="text-sm font-black mt-1">${x.title}</div><div class="text-[11px] text-slate-500 mt-1">${x.body}</div></div>`).join('')}
window.loadActivity=async()=>{if(typeof personId==='undefined'||!personId)return;let {data,error}=await sb.from('bizfit_activity_records').select('id,activity_date,title,activity_type,event_id,minutes').eq('person_id',personId).order('activity_date',{ascending:false});if(error){$('recentActivityMember').innerHTML='<p class="text-xs text-slate-400 py-4">活動記録を読み込めませんでした。</p>';return}records=data||[];summary();calendar();milestone();recent();journey()};
const base=window.showPage;window.showPage=n=>{base(n);if(n==='activity')window.loadActivity()};calendar();milestone();recent();journey();
let tries=0,t=setInterval(()=>{tries++;if(typeof personId!=='undefined'&&personId){clearInterval(t);window.loadActivity()}if(tries>40)clearInterval(t)},250);
})();